#%RAML 1.0
---
title: Arrêt sur images
baseUri: https://api.arretsurimages.net/api/public/

securitySchemes:
  oauth_2_0:
    type: OAuth 2.0
    describedBy:
      queryParameters:
        access_token:
          description: |
             Used to send a valid OAuth 2 access token.
          type: string
      responses:
        401:
          description: |
            Token expiré. Vous devez rafraichir le token ou bien vous reconnectez.
    settings:
      accessTokenUri: https://api.arretsurimages.net/oauth/v2/token
      authorizationGrants: [ client_credentials ]

traits:
  paginate:
    headers:
      range:
        required: false
        example: object 10-19

types:
  Dossier:
    type: object
    properties:
      name:
        required: true
        type: string
      slug:
        required: true
        type: string
      description:
        required: true
        type: string
    example: |
      {
        "slug": "folder-name",
        "name": "Folder name",
        "description": "The description of the folder"
      }

  Dossiers:
    type: Dossier[]

  Blog:
    type: object
    properties:
      title:
        required: true
        type: string
      slug:
        required: true
        type: string
      description:
        required: true
        type: string

  Blogs:
    type: Blog[]

/media/{mediaName}:
  get:
    responses:
      200:

/search:
  get:
    is: [ paginate ]
    queryParameters:
      format:
        type: string
        required: false
        example: chronique
      theme:
        type: string
        required: false
      q:
        description: the query
        type: string
        required: false
    responses:
      206:
        headers:
          Content-Range:
            description: the range available
            example: 'Content-Range: objects 10-1987'

/contents/{type}/{slug}:
  get:
    responses:
      200:

/authors:
  get:
    is: [ paginate ]

  /{authorName}:
    get:
      is: [ paginate ]
      responses:
        200:

/themes:
  get:
    is: [ paginate ]
    responses:
      200:

  /{themeName}:
    get:
      is: [ paginate ]
      responses:
        200:

/dossiers:
  get:
    is: [ paginate ]
    responses:
      200:
        body:
          application/json:
            type: Dossiers

  /{dossierName}:
    get:
      responses:
          200:
            body:
              application/json:
                type: Dossier

    /contents:
      get:
        is: [ paginate ]
        responses:
          200:

/blogs:
  get:
    is: [ paginate ]
    responses:
      200:
        body:
          application/json:
            type: Blogs

  /{blogName}:
    get:
      responses:
        200:
          body:
              application/json:
                type: Blog

    /contents:
      is: [ paginate ]
      get:
        responses:
          200:
