#%RAML 1.0
---
title: Arrêt sur images
baseUri: https://api.arretsurimages.net/api/public/

securitySchemes:
  oauth_2_0:
    type: OAuth 2.0
    describedBy:
      queryParameters:
        access_token:
          description: |
             Used to send a valid OAuth 2 access token.
          type: string
      responses:
        401:
          description: |
            Token expiré. Vous devez rafraichir le token ou bien vous reconnectez.
    settings:
      accessTokenUri: https://api.arretsurimages.net/oauth/v2/token
      authorizationGrants: [ client_credentials ]

traits:
  paginate:
    headers:
      Range:
        required: false
        example: object 10-19

types:
  Dossier:
    type: object
    properties:
      uuid:
        required: true
        type: string
      name:
        required: true
        type: string
      slug:
        required: true
        type: string
      description:
        required: true
        type: string
      content_count:
        required: true
        type: integer
      first_publication_at:
        required: true
        type: datetime
      is_online:
        type: boolean
        required: true
      creator:
        required: false
        type: object
      cover:
        required: true
        type: Media
      themes:
        required: false
        type: array
    example: |
      {
        "creator": {
          "nickname": "admin",
          "uuid": "3ee26ec9-82b0-49d6-b395-33ac8f6ee501"
        },
        "cover": {
          "name": "classe télé",
          "description": "",
          "mime_type": "image/png",
          "extension": "png",
          "provider": "image",
          "updated_at": "2017-12-15T10:09:33+01:00",
          "uuid": "02b89515-341e-4b0d-8fe4-32046f656fca",
          "slug": "classe-tele-3",
          "mimeType": "image/png"
        },
        "themes": [
          {
            "name": "Pédagogie & éducation",
            "is_online": true,
            "sortable_rank": 13,
            "uuid": "bb47040c-3e08-496f-8b68-67f20f0c1731",
            "slug": "education"
          }
        ],
        "name": "Classe télé&nbsp;: les collégiens démontent l'actu",
        "description": "Pub déguisée sur Twitter, mise en scène de François Hollande avec une retraitée ou rumeurs sur les migrants qui circulent sur le web : comment réagissent des collégiens face aux manipulations médiatiques ? C'est l'objet de nos \"Classe télé\" tournées au collège Gérard Philipe, à Paris.",
        "is_online": true,
        "uuid": "6318fe62-76f1-44a9-bfae-2f764583f772",
        "slug": "classe-tele-nbsp-les-collegiens-demontent-lactu",
        "first_publication_at": "2015-06-01T17:21:23+02:00",
        "content_count": 32
      }


  Dossiers:
    type: Dossier[]
    example: |
      [
        {
          "cover": {
            "name": "classe télé",
            "description": "",
            "mime_type": "image/png",
            "extension": "png",
            "provider": "image",
            "updated_at": "2017-12-15T10:09:33+01:00",
            "uuid": "02b89515-341e-4b0d-8fe4-32046f656fca",
            "slug": "classe-tele-3",
            "mimeType": "image/png"
          },
          "name": "Classe télé&nbsp;: les collégiens démontent l'actu",
          "description": "Pub déguisée sur Twitter, mise en scène de François Hollande avec une retraitée ou rumeurs sur les migrants qui circulent sur le web : comment réagissent des collégiens face aux manipulations médiatiques ? C'est l'objet de nos \"Classe télé\" tournées au collège Gérard Philipe, à Paris.",
          "is_online": true,
          "uuid": "6318fe62-76f1-44a9-bfae-2f764583f772",
          "slug": "classe-tele-nbsp-les-collegiens-demontent-lactu",
          "first_publication_at": "2015-06-01 17:21:23",
          "content_count": 32
        }
      ]

  Media:
    type: object
    properties:
      name:
        required: true
        type: string
      description:
        required: false
        type: string
      mime_type:
        required: true
        type: string
      extension:
        required: false
        type: string
      provider:
        required: true
        type: string
      updated_at:
        required: true
        type: datetime
      uuid:
        required: true
        type: string
      slug:
        required: true
        type: string
      mimeType:
        required: false
        type: string
      reference_url:
        required: false
        type: string
      video_download_link:
        required: false
        type: string
      video_duration:
        required: false
        type: integer
      cover:
        required: false
        type: Media
      metas:
        required: false
        type: object
      tags:
        required: false
        type: array
      themes:
        required: false
        type: array

  Blog:
    type: object
    properties:
      uuid:
        required: true
        type: string
      title:
        required: true
        type: string
      slug:
        required: true
        type: string
      description:
        required: false
        type: string
      created_at:
        required: true
        type: datetime
      first_publication_at:
        required: false
        type: datetime
      last_publication_at:
        required: false
        type: datetime
      is_archive:
        required: true
        type: boolean
      is_online:
        required: true
        type: boolean
      thumbnail:
        required: true
        type: Media
      cover:
        required: false
        type: Media
      themes:
        required: false
        type: array
    example: |
      {
        "themes": [],
        "cover": {
          "name": "390x390_0000_DANIEL-02",
          "description": "",
          "mime_type": "image/png",
          "extension": "png",
          "provider": "image",
          "updated_at": "2017-12-18T16:38:01+01:00",
          "uuid": "125bc6f3-1878-4880-9f3f-7a97582540f2",
          "slug": "390x390_0000_daniel-02",
          "mimeType": "image/png"
        },
        "thumbnail": {
          "name": "DANIEL Matinaute Bannière",
          "description": "",
          "mime_type": "image/png",
          "extension": "png",
          "provider": "image",
          "updated_at": "2017-11-23T18:36:32+01:00",
          "uuid": "89d8abf4-3b8b-4453-9776-8efa5ab91303",
          "slug": "daniel-matinaute-banniere",
          "mimeType": "image/png"
        },
        "title": "Le matinaute",
        "is_archive": false,
        "is_online": true,
        "created_at": "2017-10-17T17:43:00+02:00",
        "uuid": "e4cbc781-c888-4f50-893c-3e1979b73ee7",
        "slug": "le-matinaute",
        "first_publication_at": "2008-06-16T09:32:58+02:00",
        "last_publication_at": "2018-02-21 10:34:47"
      }

  Blogs:
    type: Blog[]
    example: |
      [
          {
            "thumbnail": {
              "name": "DANIEL Matinaute Bannière",
              "description": "",
              "mime_type": "image/png",
              "extension": "png",
              "provider": "image",
              "updated_at": "2017-11-23T18:36:32+01:00",
              "uuid": "89d8abf4-3b8b-4453-9776-8efa5ab91303",
              "slug": "daniel-matinaute-banniere",
              "mimeType": "image/png"
            },
            "title": "Le matinaute",
            "is_archive": false,
            "is_online": true,
            "created_at": "2017-10-17T17:43:00+02:00",
            "uuid": "e4cbc781-c888-4f50-893c-3e1979b73ee7",
            "slug": "le-matinaute",
            "last_publication_at": "2018-02-21 10:34:47"
          }
      ]

  Author:
    type: object
    properties:
      uuid:
        required: true
        type: string
      slug:
        required: true
        type: string
      name:
        required: true
        type: string
      twitter_nickname:
        required: true
        type: string
      is_online:
        required: true
        type: boolean
      picture:
        required: true
        type: Media
      blogs:
        required: false
        type: Blogs
    example: |
      {
        "blogs": [
          {
            "thumbnail": {
              "name": "daniel-bis",
              "description": "",
              "mime_type": "image/jpeg",
              "extension": "jpg",
              "provider": "image",
              "updated_at": "2017-12-07T19:55:34+01:00",
              "uuid": "ac9e0202-170b-4f23-837e-189f629e58e6",
              "slug": "daniel-bis",
              "mimeType": "image/jpeg"
            },
            "title": "Initiales DS",
            "is_archive": false,
            "is_online": true,
            "created_at": "2017-10-17T17:43:00+02:00",
            "uuid": "57dc57e1-d1b4-447d-9d3b-5a6da4002b77",
            "slug": "initiales-ds"
          },
          {
            "thumbnail": {
              "name": "DANIEL Matinaute Bannière",
              "description": "",
              "mime_type": "image/png",
              "extension": "png",
              "provider": "image",
              "updated_at": "2017-11-23T18:36:32+01:00",
              "uuid": "89d8abf4-3b8b-4453-9776-8efa5ab91303",
              "slug": "daniel-matinaute-banniere",
              "mimeType": "image/png"
            },
            "title": "Le matinaute",
            "is_archive": false,
            "is_online": true,
            "created_at": "2017-10-17T17:43:00+02:00",
            "uuid": "e4cbc781-c888-4f50-893c-3e1979b73ee7",
            "slug": "le-matinaute"
          }
        ],
        "picture": {
          "name": "daniel",
          "description": "",
          "mime_type": "image/png",
          "extension": "png",
          "provider": "image",
          "updated_at": "2017-12-06T18:15:55+01:00",
          "uuid": "e8e4e525-ceaf-4192-bab6-b861822ee26d",
          "slug": "daniel-2",
          "mimeType": "image/png"
        },
        "name": "Daniel Schneidermann",
        "twitter_nickname": "d_schneidermann",
        "is_online": true,
        "uuid": "e322813c-1f85-407f-85d2-354f10afe2e6",
        "slug": "daniel-schneidermann"
      }


  Authors:
    type: Author[]
    example: |
      [
        {
          "picture": {
            "name": "daniel",
            "description": "",
            "mime_type": "image/png",
            "extension": "png",
            "provider": "image",
            "updated_at": "2017-12-06T18:15:55+01:00",
            "uuid": "e8e4e525-ceaf-4192-bab6-b861822ee26d",
            "slug": "daniel-2",
            "mimeType": "image/png"
          },
          "name": "Daniel Schneidermann",
          "twitter_nickname": "d_schneidermann",
          "is_online": true,
          "uuid": "e322813c-1f85-407f-85d2-354f10afe2e6",
          "slug": "daniel-schneidermann"
        }
      ]

  Theme:
    type: object
    properties:
      uuid:
        required: true
        type: string
      name:
        required: true
        type: string
      slug:
        required: true
        type: string
      is_online:
        required: true
        type: boolean
      sortable_rank:
        required: true
        type: integer
    example: |
     {
       "name": "Intox & infaux",
       "is_online": true,
       "sortable_rank": 1,
       "uuid": "ac8a59b5-01ba-44fc-8896-b0d1d1888bff",
       "slug": "intox-infaux"
     }

  Themes:
    type: Theme[]
    example: |
      [
        {
          "name": "Intox & infaux",
          "is_online": true,
          "sortable_rank": 1,
          "uuid": "ac8a59b5-01ba-44fc-8896-b0d1d1888bff",
          "slug": "intox-infaux"
        }
      ]

  Content:
    type: object
    properties:
      uuid:
        required: true
        type: string
      slug:
        required: true
        type: string
      path:
        required: true
        type: string
      title:
        required: true
        type: string
      lead:
        required: true
        type: string
      subtitle:
        required: true
        type: string
      tease:
        required: true
        type: string
      blog:
        required: false
        type: Blog
      themes:
        required: false
        type: Themes
      is_elected:
        required: true
        type: boolean
      access_level:
        required: true
        type: string
      current_access_level:
        required: true
        type: string
      status:
        required: true
        type: string
      published_at:
        required: true
        type: datetime
      last_version_at:
        required: true
        type: datetime
      created_at:
        required: true
        type: datetime
      updated_at:
        required: true
        type: datetime
      authors:
        required: true
        type: Authors
      thumbnail:
        required: true
        type: Media
    example: |
      {
        "thumbnail": {
          "name": "Wauquiez Elkrief",
          "mime_type": "image/jpeg",
          "extension": "jpg",
          "provider": "image",
          "updated_at": "2018-02-21T09:26:07+01:00",
          "uuid": "851c3ccf-a3db-4944-8b89-e0902e65be4e",
          "slug": "wauquiez-elkrief",
          "mimeType": "image/jpeg"
        },
        "blog": {
          "thumbnail": {
            "name": "DANIEL Matinaute Bannière",
            "description": "",
            "mime_type": "image/png",
            "extension": "png",
            "provider": "image",
            "updated_at": "2017-11-23T18:36:32+01:00",
            "uuid": "89d8abf4-3b8b-4453-9776-8efa5ab91303",
            "slug": "daniel-matinaute-banniere",
            "mimeType": "image/png"
          },
          "title": "Le matinaute",
          "is_archive": false,
          "is_online": true,
          "created_at": "2017-10-17T17:43:00+02:00",
          "uuid": "e4cbc781-c888-4f50-893c-3e1979b73ee7",
          "slug": "le-matinaute"
        },
        "title": "Le vrai bullshit : la feuille de paie ?",
        "is_elected": false,
        "access_level": "free",
        "status": "published",
        "published_at": "2018-02-21T09:23:05+01:00",
        "last_version_at": "2018-02-21T10:34:47+01:00",
        "created_at": "2018-02-21T08:18:31+01:00",
        "updated_at": "2018-02-21T10:36:39+01:00",
        "uuid": "4f590149-9ea7-4b28-a7e3-11535abbf12c",
        "slug": "le-vrai-bullshit-la-feuille-de-paie",
        "authors": [
          {
            "picture": {
              "name": "daniel",
              "description": "",
              "mime_type": "image/png",
              "extension": "png",
              "provider": "image",
              "updated_at": "2017-12-06T18:15:55+01:00",
              "uuid": "e8e4e525-ceaf-4192-bab6-b861822ee26d",
              "slug": "daniel-2",
              "mimeType": "image/png"
            },
            "name": "Daniel Schneidermann",
            "twitter_nickname": "d_schneidermann",
            "is_online": true,
            "uuid": "e322813c-1f85-407f-85d2-354f10afe2e6",
            "slug": "daniel-schneidermann"
          }
        ],
        "lead": "",
        "subtitle": "",
        "tease": "Résumons. Laurent Wauquiez a fâché le MEDEF. Wauquiez a courroucé Christophe Barbier. Wauquiez vient triomphalement bullshiter Ruth Elkrief. \"Vous savez ce que je crois, Ruth Elkrief ?\" \"Vous m'autori...",
        "current_access_level": "free",
        "content_type": {
          "content_format": {
            "label": "Chronique",
            "uuid": "e912c0ec-e807-4d61-b0ee-26867e1afc59",
            "slug": "chronique",
            "plural": "chroniques"
          },
          "label": "chronique",
          "is_default": false,
          "uuid": "a7544def-07ce-4cff-b8b8-daf154b967c5",
          "slug": "chronique"
        },
        "path": "chroniques/le-vrai-bullshit-la-feuille-de-paie"
      }

  Contents:
    type: Content[]

/media/{mediaName}:
  get:
    responses:
      200:

/search:
  get:
    is: [ paginate ]
    queryParameters:
      format:
        type: string
        required: false
        example: chronique
      theme:
        type: string
        required: false
      author:
        type: string
        required: false
      q:
        description: the query
        type: string
        required: false
    responses:
      206:
        headers:
          Content-Range:
            description: the range available
            example: 'Content-Range: objects 10-1987'

/contents/{type}/{slug}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Contents

/authors:
  get:
    is: [ paginate ]
    responses:
      200:
        headers:
          Content-Range:
            description: the range available
            example: 'Content-Range: objects 10-1987'
        body:
          application/json:
            type: Authors

  /{authorName}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Author

/themes:
  get:
    is: [ paginate ]
    responses:
      200:
        headers:
          Content-Range:
            description: the range available
            example: 'Content-Range: objects 10-1987'
        body:
          application/json:
            type: Themes

  /{themeName}:
    get:
      responses:
        200:
          body:
            application/json:
                type: Theme

/dossiers:
  get:
    is: [ paginate ]
    responses:
      200:
        headers:
          Content-Range:
            description: the range available
            example: 'Content-Range: objects 10-1987'
        body:
          application/json:
            type: Dossiers

  /{dossierName}:
    get:
      responses:
          200:
            body:
              application/json:
                type: Dossier

    /contents:
      get:
        is: [ paginate ]
        responses:
          200:
            headers:
              Content-Range:
                description: the range available
                example: 'Content-Range: objects 10-1987'
            body:
              application/json:
                type: Contents

/blogs:
  get:
    is: [ paginate ]
    responses:
      200:
        headers:
          Content-Range:
            description: the range available
            example: 'Content-Range: objects 10-1987'
        body:
          application/json:
            type: Blogs

  /{blogName}:
    get:
      responses:
        200:
          body:
              application/json:
                type: Blog

    /contents:
      is: [ paginate ]
      get:
        responses:
          200:
            headers:
              Content-Range:
                description: the range available
                example: 'Content-Range: objects 10-1987'
            body:
              application/json:
                type: Contents
