#!/bin/sh

PHOENIX_IMAGE=bitwalker/alpine-elixir-phoenix:1.8.1

DOCKER_RUN_ARGS="--rm --volume $(pwd):/code --workdir /code $PHOENIX_IMAGE"

docker run $DOCKER_RUN_ARGS sh -c "mix do deps.get"
docker run $DOCKER_RUN_ARGS sh -c "cd assets && npm install"
docker run --interactive --tty --publish 4000:4000 $DOCKER_RUN_ARGS sh -c "mix phx.server"
